[workspace]
members = ["audio_server", "reachy-api"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["Pollen Robotics"]
description = "Reachy 2 SDK Audio Server"
documentation = "https://www.pollen-robotics.com"
